version: "3.8"

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "db"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - default
  django:
    ports:
      - "8000:8000"
    build:
      context: ./tvshowratinganalyzer
      dockerfile: ./Dockerfile
    networks:
      - default
    environment:
      DB_HOST: "localhost"
      DB_PORT: "5432"
      DB_NAME: "db"
      DB_USER: "user"
      DB_PASSWORD: "password"
    depends_on:
      - db
